baseurl: "/redoc"
apiname: "Haal Centraal"
url: "http://localhost:4000"

nav:
  - title: Bewoning
    subnav:
#     - title: v2
        path: /bewoning-v2
      - title: v2 GBA
        path: /bewoning-v2-gba
  - title: Reisdocumenten
    subnav:
#     - title: v2
        path: /reisdocumenten-v2
      - title: v2 GBA
        path: /reisdocumenten-v2-gba
plugins:
  - jekyll-redirect-from
  - jekyll-remote-theme

remote_theme: VNG-Realisatie/jekyll-theme-haal-centraal

github: fsamwel/redoc

theme: jekyll-theme-time-machine

project_name: /Haal-Centraal
